//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.AddInSideAdapters
{
    
    public class IPipelineEventEventHandlerContractToViewAddInAdapter
    {
        private Guanwu.Notify.IPipelineEventEventHandlerContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        public IPipelineEventEventHandlerContractToViewAddInAdapter(Guanwu.Notify.IPipelineEventEventHandlerContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public void Handler(object sender, Guanwu.Notify.Views.PipelineEventEventArgs args)
        {
            _contract.EventHandler(Guanwu.Notify.AddInSideAdapters.PipelineEventEventArgsAddInAdapter.ViewToContractAdapter(args));
        }
        internal Guanwu.Notify.IPipelineEventEventHandlerContract GetSourceContract()
        {
            return _contract;
        }
    }
}

