//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.AddInSideAdapters
{
    
    public class IPluginAddInAdapter
    {
        internal static Guanwu.Notify.Views.IPlugin ContractToViewAdapter(Guanwu.Notify.IPluginContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IPluginViewToContractAddInAdapter))))
            {
                return ((IPluginViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IPluginContractToViewAddInAdapter(contract);
            }
        }
        internal static Guanwu.Notify.IPluginContract ViewToContractAdapter(Guanwu.Notify.Views.IPlugin view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IPluginContractToViewAddInAdapter)))
            {
                return ((IPluginContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IPluginViewToContractAddInAdapter(view);
            }
        }
    }
}

