//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.AddInSideAdapters
{
    
    public class IPluginObjectAddInAdapter
    {
        internal static Guanwu.Notify.Views.IPluginObject ContractToViewAdapter(Guanwu.Notify.IPluginObjectContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IPluginObjectViewToContractAddInAdapter))))
            {
                return ((IPluginObjectViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IPluginObjectContractToViewAddInAdapter(contract);
            }
        }
        internal static Guanwu.Notify.IPluginObjectContract ViewToContractAdapter(Guanwu.Notify.Views.IPluginObject view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IPluginObjectContractToViewAddInAdapter)))
            {
                return ((IPluginObjectContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IPluginObjectViewToContractAddInAdapter(view);
            }
        }
    }
}

