//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.AddInSideAdapters
{
    
    public class PipelineMessageEventArgsAddInAdapter
    {
        internal static Guanwu.Notify.Views.PipelineMessageEventArgs ContractToViewAdapter(Guanwu.Notify.IPipelineMessageEventArgsContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(PipelineMessageEventArgsViewToContractAddInAdapter))))
            {
                return ((PipelineMessageEventArgsViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new PipelineMessageEventArgsContractToViewAddInAdapter(contract);
            }
        }
        internal static Guanwu.Notify.IPipelineMessageEventArgsContract ViewToContractAdapter(Guanwu.Notify.Views.PipelineMessageEventArgs view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(PipelineMessageEventArgsContractToViewAddInAdapter)))
            {
                return ((PipelineMessageEventArgsContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new PipelineMessageEventArgsViewToContractAddInAdapter(view);
            }
        }
    }
}

