//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.AddInSideAdapters
{
    
    public class PipelineEventEventArgsAddInAdapter
    {
        internal static Guanwu.Notify.Views.PipelineEventEventArgs ContractToViewAdapter(Guanwu.Notify.IPipelineEventEventArgsContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(PipelineEventEventArgsViewToContractAddInAdapter))))
            {
                return ((PipelineEventEventArgsViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new PipelineEventEventArgsContractToViewAddInAdapter(contract);
            }
        }
        internal static Guanwu.Notify.IPipelineEventEventArgsContract ViewToContractAdapter(Guanwu.Notify.Views.PipelineEventEventArgs view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(PipelineEventEventArgsContractToViewAddInAdapter)))
            {
                return ((PipelineEventEventArgsContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new PipelineEventEventArgsViewToContractAddInAdapter(view);
            }
        }
    }
}

