//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.HostSideAdapters
{
    
    public class IPluginHostAdapter
    {
        internal static Guanwu.Notify.Views.IPlugin ContractToViewAdapter(Guanwu.Notify.IPluginContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IPluginViewToContractHostAdapter))))
            {
                return ((IPluginViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IPluginContractToViewHostAdapter(contract);
            }
        }
        internal static Guanwu.Notify.IPluginContract ViewToContractAdapter(Guanwu.Notify.Views.IPlugin view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IPluginContractToViewHostAdapter)))
            {
                return ((IPluginContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IPluginViewToContractHostAdapter(view);
            }
        }
    }
}

