//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.HostSideAdapters
{
    
    public class PipelineEventEventArgsHostAdapter
    {
        internal static Guanwu.Notify.Views.PipelineEventEventArgs ContractToViewAdapter(Guanwu.Notify.IPipelineEventEventArgsContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(PipelineEventEventArgsViewToContractHostAdapter))))
            {
                return ((PipelineEventEventArgsViewToContractHostAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new PipelineEventEventArgsContractToViewHostAdapter(contract);
            }
        }
        internal static Guanwu.Notify.IPipelineEventEventArgsContract ViewToContractAdapter(Guanwu.Notify.Views.PipelineEventEventArgs view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(PipelineEventEventArgsContractToViewHostAdapter)))
            {
                return ((PipelineEventEventArgsContractToViewHostAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new PipelineEventEventArgsViewToContractHostAdapter(view);
            }
        }
    }
}

