//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.HostSideAdapters
{
    
    public class PipelineMessageEventArgsContractToViewHostAdapter : Guanwu.Notify.Views.PipelineMessageEventArgs
    {
        private Guanwu.Notify.IPipelineMessageEventArgsContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static PipelineMessageEventArgsContractToViewHostAdapter()
        {
        }
        public PipelineMessageEventArgsContractToViewHostAdapter(Guanwu.Notify.IPipelineMessageEventArgsContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public override Guanwu.Notify.Views.PipelineMessage Message
        {
            get
            {
                return Guanwu.Notify.HostSideAdapters.PipelineMessageHostAdapter.ContractToViewAdapter(_contract.Message);
            }
            set
            {
                _contract.Message = Guanwu.Notify.HostSideAdapters.PipelineMessageHostAdapter.ViewToContractAdapter(value);
            }
        }
        internal Guanwu.Notify.IPipelineMessageEventArgsContract GetSourceContract()
        {
            return _contract;
        }
    }
}

