//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.HostSideAdapters
{
    
    public class PipelineEventEventArgsViewToContractHostAdapter : System.AddIn.Pipeline.ContractBase, Guanwu.Notify.IPipelineEventEventArgsContract
    {
        private Guanwu.Notify.Views.PipelineEventEventArgs _view;
        public PipelineEventEventArgsViewToContractHostAdapter(Guanwu.Notify.Views.PipelineEventEventArgs view)
        {
            _view = view;
        }
        public Guanwu.Notify.PipelineEvent Event
        {
            get
            {
                return Guanwu.Notify.HostSideAdapters.PipelineEventHostAdapter.ViewToContractAdapter(_view.Event);
            }
            set
            {
                _view.Event = Guanwu.Notify.HostSideAdapters.PipelineEventHostAdapter.ContractToViewAdapter(value);
            }
        }
        internal Guanwu.Notify.Views.PipelineEventEventArgs GetSourceView()
        {
            return _view;
        }
    }
}

