//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.HostSideAdapters
{
    
    public class PipelineMessageEventArgsViewToContractHostAdapter : System.AddIn.Pipeline.ContractBase, Guanwu.Notify.IPipelineMessageEventArgsContract
    {
        private Guanwu.Notify.Views.PipelineMessageEventArgs _view;
        public PipelineMessageEventArgsViewToContractHostAdapter(Guanwu.Notify.Views.PipelineMessageEventArgs view)
        {
            _view = view;
        }
        public Guanwu.Notify.PipelineMessage Message
        {
            get
            {
                return Guanwu.Notify.HostSideAdapters.PipelineMessageHostAdapter.ViewToContractAdapter(_view.Message);
            }
            set
            {
                _view.Message = Guanwu.Notify.HostSideAdapters.PipelineMessageHostAdapter.ContractToViewAdapter(value);
            }
        }
        internal Guanwu.Notify.Views.PipelineMessageEventArgs GetSourceView()
        {
            return _view;
        }
    }
}

