//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.HostSideAdapters
{
    
    public class PipelineEventHostAdapter
    {
        public static Guanwu.Notify.Views.PipelineEvent ContractToViewAdapter(Guanwu.Notify.PipelineEvent contract)
        {
            return new Guanwu.Notify.Views.PipelineEvent(contract.Id, contract.Sender, contract.EventName, System.AddIn.Pipeline.CollectionAdapters.ToIList<string>(contract.EventArgs));
        }
        public static Guanwu.Notify.PipelineEvent ViewToContractAdapter(Guanwu.Notify.Views.PipelineEvent view)
        {
            return new Guanwu.Notify.PipelineEvent(view.Id, view.Sender, view.EventName, System.AddIn.Pipeline.CollectionAdapters.ToIListContract<string>(view.EventArgs));
        }
    }
}

