//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.HostSideAdapters
{
    
    public class PipelineMessageArrayHostAdapter
    {
        public static Guanwu.Notify.Views.PipelineMessage[] ContractToViewAdapter(Guanwu.Notify.PipelineMessage[] contract)
        {
            if ((contract == null))
            {
                return null;
            }
            Guanwu.Notify.Views.PipelineMessage[] result = new Guanwu.Notify.Views.PipelineMessage[contract.Length];
            for (int i = 0; (i < contract.Length); i = (i + 1))
            {
                result[i] = Guanwu.Notify.HostSideAdapters.PipelineMessageHostAdapter.ContractToViewAdapter(contract[i]);
            }
            return result;
        }
        public static Guanwu.Notify.PipelineMessage[] ViewToContractAdapter(Guanwu.Notify.Views.PipelineMessage[] view)
        {
            if ((view == null))
            {
                return null;
            }
            Guanwu.Notify.PipelineMessage[] result = new Guanwu.Notify.PipelineMessage[view.Length];
            for (int i = 0; (i < view.Length); i = (i + 1))
            {
                result[i] = Guanwu.Notify.HostSideAdapters.PipelineMessageHostAdapter.ViewToContractAdapter(view[i]);
            }
            return result;
        }
    }
}

