//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.Views
{
    
    [System.AddIn.Pipeline.AddInBaseAttribute()]
    public interface IPlugin
    {
        void Initialize(IPluginObject pluginObject);
        void Execute();
    }
}

