//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.Views
{
    
    public interface IPluginObject
    {
        event System.EventHandler<PipelineMessageEventArgs> OnMessageReceived;
        event System.EventHandler<PipelineMessageEventArgs> OnMessagePersisting;
        event System.EventHandler<PipelineMessageEventArgs> OnMessagePersisted;
        event System.EventHandler<PipelineEventEventArgs> OnEventRaising;
        event System.EventHandler<PipelineEventEventArgs> OnEventRaised;
        void ReceiveMessage(PipelineMessage pMessage);
        void PersistingMessage(PipelineMessage pMessage);
        void PersistedMessage(PipelineMessage pMessage);
        void RaisingEvent(PipelineEvent pEvent);
        void RaisedEvent(PipelineEvent pEvent);
    }
}

