//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guanwu.Notify.Views
{
    
    public struct PipelineMessage
    {
        private string _id;
        private string _content;
        private string _source;
        private System.Collections.Generic.IList<string> _targets;
        public PipelineMessage(string id, string content, string source, System.Collections.Generic.IList<string> targets)
        {
            _id = id;
            _content = content;
            _source = source;
            _targets = targets;
        }
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
        public string Content
        {
            get
            {
                return _content;
            }
            set
            {
                _content = value;
            }
        }
        public string Source
        {
            get
            {
                return _source;
            }
            set
            {
                _source = value;
            }
        }
        public System.Collections.Generic.IList<string> Targets
        {
            get
            {
                return _targets;
            }
            set
            {
                _targets = value;
            }
        }
    }
}

